name: Android CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - '!*-RuStore'

permissions:
  contents: write

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Checkout keystore repo
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
         ./gradlew assembleRelease  --stacktrace
         ./gradlew bundleRelease
    - name: Release to RuStore
      run: |
        KEY_ID="${{ secrets.RUSTORE_KEY_ID }}"
        # Извлекаем приватный ключ из секрета и декодируем
        PRIVATE_KEY_BASE64="${{ secrets.RUSTORE_KEY }}"
        echo $PRIVATE_KEY_BASE64 | base64 --decode > private_key.pem
        # Генерация timestamp
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
        # Создаем сообщение для подписи
        MESSAGE="${KEY_ID}${TIMESTAMP}"
        # Генерация подписи с помощью OpenSSL
        SIGNATURE=$(echo -n "$MESSAGE" | openssl dgst -sha512 -sign private_key.pem | base64)
        echo "Signature: $SIGNATURE"  
        # Получение JWT токена
        RESPONSE=$(curl --location --request POST 'https://public-api.rustore.ru/public/auth' \
          --header 'Content-Type: application/json' \
          --data '{
            "keyId": "'"${KEY_ID}"'",
            "timestamp": "'"${TIMESTAMP}"'",
            "signature": "'"${SIGNATURE}"'"
          }')
        # Извлекаем jwe из ответа
        JWT_TOKEN=$(echo $RESPONSE | jq -r '.body.jwe')
        # Публикуем apk
        APP_PACKAGE_NAME="top.rootu.lampa" # пакет приложения
        APK_PATH="./app/build/outputs/apk/ruStore/release/app-ruStore-release.apk" # Путь к APK
        VERSION_CODE=$(git rev-list --count origin/main) # versionCode
        curl --location --request POST "https://public-api.rustore.ru/public/v1/application/${APP_PACKAGE_NAME}/version/${VERSION_CODE}/apk?servicesType=Unknown&isMainApk=true" \
          --header "Public-Token: ${JWT_TOKEN}" \
          --form "file=@\"${APK_PATH}\""
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app/build/outputs/apk/lite/release/app-lite-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
